<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Cui Christina, Jiajia Feng, Jiahui He, William Mahnke">
<meta name="dcterms.date" content="2024-10-30">

<title>Biomarkers of ASD</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biomarkers of ASD</h1>
<p class="subtitle lead">If you want a subtitle put it here</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Cui Christina, Jiajia Feng, Jiahui He, William Mahnke </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Updated</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 30, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Use this as a template. Keep the headers and remove all other text. In all, your report can be quite short. When it is complete, render and then push changes to your team repository.</p>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This report presents a proteomic analysis of serum data aimed at identifying candidate biomarkers for the early detection of autism spectrum disorder (ASD), building on the methodology of Hewitson et al.&nbsp;(2021). We evaluate the effects of various methodological adjustments, including log-transformation of protein levels, outlier handling without data trimming, and the use of a reserved testing partition. To enhance predictive performance, we apply a fuzzy intersection approach for protein selection, constructing refined and alternative panels optimized for classification accuracy. Our findings are compared to previous analyses to assess the robustness and sensitivity of each methodological adjustment.</p>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<p>The dataset includes proteomic measurements from serum samples to identify biomarkers associated with autism spectrum disorder (ASD). It consists of 156 samples and 1,320 variables, each representing different protein levels measured in arbitrary units. Key variables include group classifications (e.g., ASD or TD), specific protein levels, and assessment scores like the ADOS Total Score. Data preprocessing for this analysis involved log-transformation of protein levels, handling outliers without trimming, and splitting into training and testing partitions. This approach enables effective feature selection and classification accuracy assessment for candidate biomarkers.</p>
</section>
<section id="summary-of-published-analysis" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-published-analysis">Summary of published analysis</h2>
<p>The paper combines statistical tests and machine learning to identify key protein biomarkers associated with a specific condition. It starts with univariate T-tests to evaluate each protein’s association with the condition, narrowing down the most significant proteins. Next, Random Forest and Logistic Regression models prioritize these proteins based on feature importance scores and coefficient values, respectively. This dual-model approach helps identify proteins with the greatest predictive potential.</p>
<p>The analysis identified distinct sets of top proteins for each method. For the T-test selection, the key proteins included <strong>PTN, RELT, MAPK2, DERM, Calcineurin, M2-PK, TFF3, FSTL1, CXCL16, MAPK14, Coagulation Factor IX, IgD, MIA, Fas, MMP-2, IGFBP-4, ROR1, Protein S, 14-3-3 protein zeta/delta</strong>, and <strong>TGF-b R III</strong>, yielding an accuracy of <strong>72.05%</strong> on the testing data. The Random Forest model, achieving an accuracy of <strong>78.95%</strong>, selected proteins such as <strong>eIF-4H, MAPK2, PTN, CSK, MAPK14, M2-PK, DERM, Lysozyme, RELT, ILT-4, CD27, Nectin-like protein 2, Coagulation Factor IX, Calcineurin, Notch 1, IgD, IGFBP-1, SOST, GPVI</strong>, and <strong>MMP-2</strong>. For Logistic Regression, the proteins included <strong>SMAD3, HXK1, Myostatin, HIF-1a, CHKB, ISLR2, CSH, HHLA2, RNF43, OAS1, TIMP-1, CD59, SMOC1, 14-3-3 protein beta/alpha, SNP25, LDLR, S100A4, EFNB1, EFNB2</strong>, and <strong>STAT6</strong>. Combining top proteins across methods via a fuzzy intersection improved the classifier accuracy to <strong>82.42%</strong>. This multi-method approach, particularly the fuzzy intersection, achieved the highest overall predictive accuracy.</p>
</section>
<section id="findings" class="level2">
<h2 class="anchored" data-anchor-id="findings">Findings</h2>
<p>Summarize your findings here. I’ve included some subheaders in a way that seems natural to me; you can structure this section however you like.</p>
<section id="impact-of-preprocessing-and-outliers" class="level3">
<h3 class="anchored" data-anchor-id="impact-of-preprocessing-and-outliers">Impact of preprocessing and outliers</h3>
</section>
<section id="question-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1">Question 1</h3>
<p>Since <code>biomarker-raw.csv</code> contains protein concentration levels across various samples, let’s examine the distribution of a sample of these protein values.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The histograms reveal that the distributions of raw protein levels are skewed right, with some values extending to higher ranges. This skewness is a common reason to apply a log transformation, which can help normalize these distributions.<br>
</p>
</section>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Group avg_outliers total_outliers subjects_with_outliers
  &lt;chr&gt;        &lt;dbl&gt;          &lt;int&gt;                  &lt;int&gt;
1 ""          0                   0                      0
2 "ASD"       0.0263              2                      2
3 "TD"        0                   0                      0</code></pre>
</div>
</div>
<section id="are-there-specific-subjects-not-values-that-seem-to-be-outliers" class="level4">
<h4 class="anchored" data-anchor-id="are-there-specific-subjects-not-values-that-seem-to-be-outliers">Are there specific subjects (not values) that seem to be outliers?</h4>
<p>Yes, there are specific subjects with outliers. According to the table of nsummary, there are 2 subjects with outlying values in the ASD group.</p>
</section>
<section id="are-outliers-more-frequent-in-one-group-or-the-other" class="level4">
<h4 class="anchored" data-anchor-id="are-outliers-more-frequent-in-one-group-or-the-other">Are outliers more frequent in one group or the other?</h4>
<p>Outliers are more frequent in the ASD group. ASD group with a total of 2 outliers, while the TD group has none.</p>
</section>
</section>
<section id="methodlogical-variations" class="level3">
<h3 class="anchored" data-anchor-id="methodlogical-variations">Methodlogical variations</h3>
</section>
<section id="question-3" class="level3">
<h3 class="anchored" data-anchor-id="question-3">Question 3</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1,319
  group  ados    CHIP  CEBPB     NSE   PIAS4 `IL-10 Ra`  STAT3   IRF1 `c-Jun`
  &lt;chr&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1 ASD       8  0.335   0.520 -0.554   0.650      -0.358  0.305 -0.484   0.309
2 ASD      21 -0.0715  1.01   3       1.28       -0.133  1.13   0.253   0.408
3 ASD      12 -0.406  -0.531 -0.0592  1.13        0.554 -0.334  0.287  -0.845
4 ASD      20 -0.102  -0.251  1.47    0.0773     -0.705  0.893  2.61   -0.372
5 ASD      22 -0.395  -0.536  0.0410 -0.299      -0.830  0.899  1.01   -0.843
6 ASD      17 -0.126   1.27  -0.892   0.239      -0.344  0.216  0.211   0.221
# ℹ 1,309 more variables: `Mcl-1` &lt;dbl&gt;, OAS1 &lt;dbl&gt;, `c-Myc` &lt;dbl&gt;,
#   SMAD3 &lt;dbl&gt;, SMAD2 &lt;dbl&gt;, `IL-23` &lt;dbl&gt;, PDGFRA &lt;dbl&gt;, `IL-12` &lt;dbl&gt;,
#   STAT1 &lt;dbl&gt;, STAT6 &lt;dbl&gt;, LRRK2 &lt;dbl&gt;, Osteocalcin &lt;dbl&gt;, `IL-5` &lt;dbl&gt;,
#   GPDA &lt;dbl&gt;, IgA &lt;dbl&gt;, LPPL &lt;dbl&gt;, HEMK2 &lt;dbl&gt;, PDXK &lt;dbl&gt;, TLR4 &lt;dbl&gt;,
#   REG4 &lt;dbl&gt;, `HSP 27` &lt;dbl&gt;, `YKL-40` &lt;dbl&gt;, `Alpha enolase` &lt;dbl&gt;,
#   `Apo L1` &lt;dbl&gt;, CD38 &lt;dbl&gt;, CD59 &lt;dbl&gt;, FABPL &lt;dbl&gt;, `GDF-11` &lt;dbl&gt;,
#   BTC &lt;dbl&gt;, `HIF-1a` &lt;dbl&gt;, S100A6 &lt;dbl&gt;, SECTM1 &lt;dbl&gt;, RSPO3 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<section id="split-training-and-testing" class="level4">
<h4 class="anchored" data-anchor-id="split-training-and-testing">Split Training and Testing</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1,319
  group  ados   CHIP  CEBPB     NSE  PIAS4 `IL-10 Ra`   STAT3    IRF1 `c-Jun`
  &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 ASD       8  0.335  0.520 -0.554   0.650     -0.358  0.305  -0.484    0.309
2 ASD      22 -0.395 -0.536  0.0410 -0.299     -0.830  0.899   1.01    -0.843
3 ASD      17 -0.126  1.27  -0.892   0.239     -0.344  0.216   0.211    0.221
4 ASD      15  0.486  0.748 -1.09    0.462      0.570 -0.0682  1.01     1.21 
5 ASD      10 -0.990 -1.10   0.231  -0.885     -0.151  0.0307 -0.0346  -0.891
6 ASD      22 -0.108  3      2.32    3          2.76   1.70    0.209    3    
# ℹ 1,309 more variables: `Mcl-1` &lt;dbl&gt;, OAS1 &lt;dbl&gt;, `c-Myc` &lt;dbl&gt;,
#   SMAD3 &lt;dbl&gt;, SMAD2 &lt;dbl&gt;, `IL-23` &lt;dbl&gt;, PDGFRA &lt;dbl&gt;, `IL-12` &lt;dbl&gt;,
#   STAT1 &lt;dbl&gt;, STAT6 &lt;dbl&gt;, LRRK2 &lt;dbl&gt;, Osteocalcin &lt;dbl&gt;, `IL-5` &lt;dbl&gt;,
#   GPDA &lt;dbl&gt;, IgA &lt;dbl&gt;, LPPL &lt;dbl&gt;, HEMK2 &lt;dbl&gt;, PDXK &lt;dbl&gt;, TLR4 &lt;dbl&gt;,
#   REG4 &lt;dbl&gt;, `HSP 27` &lt;dbl&gt;, `YKL-40` &lt;dbl&gt;, `Alpha enolase` &lt;dbl&gt;,
#   `Apo L1` &lt;dbl&gt;, CD38 &lt;dbl&gt;, CD59 &lt;dbl&gt;, FABPL &lt;dbl&gt;, `GDF-11` &lt;dbl&gt;,
#   BTC &lt;dbl&gt;, `HIF-1a` &lt;dbl&gt;, S100A6 &lt;dbl&gt;, SECTM1 &lt;dbl&gt;, RSPO3 &lt;dbl&gt;, …</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1,319
  group  ados    CHIP   CEBPB     NSE   PIAS4 `IL-10 Ra`  STAT3    IRF1 `c-Jun`
  &lt;chr&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 ASD      21 -0.0715  1.01    3       1.28       -0.133  1.13   0.253    0.408
2 ASD      12 -0.406  -0.531  -0.0592  1.13        0.554 -0.334  0.287   -0.845
3 ASD      20 -0.102  -0.251   1.47    0.0773     -0.705  0.893  2.61    -0.372
4 ASD      14 -0.378  -0.0790 -0.727   0.814      -0.811 -0.406 -0.791   -0.647
5 ASD      17  0.214   1.85    2.17    2.19       -0.102 -0.551 -0.293    1.80 
6 ASD      13  1.35   -0.947  -1.28   -0.931      -0.443 -1.32   0.0259  -0.445
# ℹ 1,309 more variables: `Mcl-1` &lt;dbl&gt;, OAS1 &lt;dbl&gt;, `c-Myc` &lt;dbl&gt;,
#   SMAD3 &lt;dbl&gt;, SMAD2 &lt;dbl&gt;, `IL-23` &lt;dbl&gt;, PDGFRA &lt;dbl&gt;, `IL-12` &lt;dbl&gt;,
#   STAT1 &lt;dbl&gt;, STAT6 &lt;dbl&gt;, LRRK2 &lt;dbl&gt;, Osteocalcin &lt;dbl&gt;, `IL-5` &lt;dbl&gt;,
#   GPDA &lt;dbl&gt;, IgA &lt;dbl&gt;, LPPL &lt;dbl&gt;, HEMK2 &lt;dbl&gt;, PDXK &lt;dbl&gt;, TLR4 &lt;dbl&gt;,
#   REG4 &lt;dbl&gt;, `HSP 27` &lt;dbl&gt;, `YKL-40` &lt;dbl&gt;, `Alpha enolase` &lt;dbl&gt;,
#   `Apo L1` &lt;dbl&gt;, CD38 &lt;dbl&gt;, CD59 &lt;dbl&gt;, FABPL &lt;dbl&gt;, `GDF-11` &lt;dbl&gt;,
#   BTC &lt;dbl&gt;, `HIF-1a` &lt;dbl&gt;, S100A6 &lt;dbl&gt;, SECTM1 &lt;dbl&gt;, RSPO3 &lt;dbl&gt;, …</code></pre>
</div>
</div>
</section>
<section id="apply-t-test-random-forest-and-logistic-regression-using-top-20-features" class="level4">
<h4 class="anchored" data-anchor-id="apply-t-test-random-forest-and-logistic-regression-using-top-20-features">Apply T-test, Random Forest, and Logistic Regression (Using Top 20 Features)</h4>
<section id="t-test-selection" class="level5">
<h5 class="anchored" data-anchor-id="t-test-selection">T-test Selection</h5>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "PTN"                       "RELT"                     
 [3] "MAPK2"                     "DERM"                     
 [5] "Calcineurin"               "M2-PK"                    
 [7] "TFF3"                      "FSTL1"                    
 [9] "CXCL16, soluble"           "MAPK14"                   
[11] "Coagulation Factor IX"     "IgD"                      
[13] "MIA"                       "Fas, soluble"             
[15] "MMP-2"                     "IGFBP-4"                  
[17] "ROR1"                      "Protein S"                
[19] "14-3-3 protein zeta/delta" "TGF-b R III"              </code></pre>
</div>
</div>
</section>
<section id="random-forest" class="level5">
<h5 class="anchored" data-anchor-id="random-forest">Random Forest</h5>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    ASD TD class.error
ASD  35 26   0.4262295
TD   13 50   0.2063492</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "eIF-4H"                "MAPK2"                 "PTN"                  
 [4] "CSK"                   "MAPK14"                "M2-PK"                
 [7] "DERM"                  "Lysozyme"              "RELT"                 
[10] "ILT-4"                 "CD27"                  "Nectin-like protein 2"
[13] "Coagulation Factor IX" "Calcineurin"           "Notch 1"              
[16] "IgD"                   "IGFBP-1"               "SOST"                 
[19] "GPVI"                  "MMP-2"                </code></pre>
</div>
</div>
</section>
<section id="logistic-regression" class="level5">
<h5 class="anchored" data-anchor-id="logistic-regression">Logistic Regression</h5>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "SMAD3"                             "HXK1"                             
 [3] "Myostatin"                         "`\\`HIF-1a\\``"                   
 [5] "CHKB"                              "ISLR2"                            
 [7] "CSH"                               "HHLA2"                            
 [9] "RNF43"                             "OAS1"                             
[11] "`\\`TIMP-1\\``"                    "CD59"                             
[13] "SMOC1"                             "`\\`14-3-3 protein beta/alpha\\``"
[15] "SNP25"                             "LDLR"                             
[17] "S100A4"                            "EFNB1"                            
[19] "EFNB2"                             "STAT6"                            </code></pre>
</div>
</div>
</section>
<section id="fuzzy-interaction" class="level5">
<h5 class="anchored" data-anchor-id="fuzzy-interaction">Fuzzy Interaction</h5>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Calcineurin"           "Coagulation Factor IX" "DERM"                 
 [4] "IgD"                   "M2-PK"                 "MAPK14"               
 [7] "MAPK2"                 "MMP-2"                 "PTN"                  
[10] "RELT"                 </code></pre>
</div>
</div>
</section>
</section>
<section id="how-are-results-affected-by-each-modification" class="level4">
<h4 class="anchored" data-anchor-id="how-are-results-affected-by-each-modification">How are results affected by each modification?</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy of T-test model on testing data: 0.720524 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy of Random Forest model on testing data: 0.7894737 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy of Fuzzy Intersection model on testing data: 0.8241758 </code></pre>
</div>
</div>
<p>Each method yields different predictive performance, with Random Forest and the Fuzzy Intersection performing similarly well. The fuzzy intersection can be a useful compromise when seeking a balance between different selection criteria, but in this case, it does not significantly outperform Random Forest alone.</p>
</section>
</section>
<section id="improved-classifier" class="level3">
<h3 class="anchored" data-anchor-id="improved-classifier">Improved classifier</h3>
<p>Accuracy of T-test model on testing data: 0.720524</p>
<p>Accuracy of Random Forest model on testing data: 0.7894737</p>
<p>Accuracy of Fuzzy Intersection model on testing data: 0.8241758</p>
<p>Each method shows varying levels of predictive accuracy, with Random Forest and the Fuzzy Intersection achieving comparable results. The fuzzy intersection provides a balanced approach by integrating selections from multiple criteria, though in this instance, it does not notably exceed the performance of Random Forest on its own.</p>
<ul>
<li><p><strong>Initial Panels</strong>: T-test, Random Forest, Logistic Regression, Fuzzy Intersection (original)</p></li>
<li><p><strong>New Panels</strong>: Simpler Panel (RFE) and Alternative Panel (modified fuzzy intersection)</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>