---
title: "Biomarkers of ASD"
subtitle: "If you want a subtitle put it here"
author: "Cui Christina, Jiajia Feng, Jiahui He, William Mahnke"
date: last-modified
published-title: "Updated"
editor: visual
format: html
code-copy: true
execute:
  message: false
  warning: false
  echo: false
  cache: true
---

Use this as a template. Keep the headers and remove all other text. In all, your report can be quite short. When it is complete, render and then push changes to your team repository.

```{r}
# load any other packages and read data here
library(tidyverse)
```

## Abstract

This report presents a proteomic analysis of serum data aimed at identifying candidate biomarkers for the early detection of autism spectrum disorder (ASD), building on the methodology of Hewitson et al. (2021). We evaluate the effects of various methodological adjustments, including log-transformation of protein levels, outlier handling without data trimming, and the use of a reserved testing partition. To enhance predictive performance, we apply a fuzzy intersection approach for protein selection, constructing refined and alternative panels optimized for classification accuracy. Our findings are compared to previous analyses to assess the robustness and sensitivity of each methodological adjustment.

## Dataset

The dataset includes proteomic measurements from serum samples to identify biomarkers associated with autism spectrum disorder (ASD). It consists of 156 samples and 1,320 variables, each representing different protein levels measured in arbitrary units. Key variables include group classifications (e.g., ASD or control), specific protein levels, and assessment scores like the ADOS Total Score. Data preprocessing for this analysis involved log-transformation of protein levels, handling outliers without trimming, and splitting into training and testing partitions. This approach enables robust feature selection and classification accuracy assessment for candidate biomarkers.

## Summary of published analysis

Summarize the methodology of the paper in 1-3 paragraphs. You need not explain the methods in depth as we did in class; just indicate what methods were used and how they were combined. If possible, include a diagram that depicts the methodological design. (Quarto has support for [GraphViz and Mermaid flowcharts](https://quarto.org/docs/authoring/diagrams.html).) Provide key results: the proteins selected for the classifier and the estimated accuracy.

## Findings

Summarize your findings here. I've included some subheaders in a way that seems natural to me; you can structure this section however you like.

### Impact of preprocessing and outliers

Tasks 1-2

### Methodlogical variations

Task 3

### Improved classifier

Task 4
